export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';

export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_FAILURE = 'DELETE_FAILURE';

export const ADD_UERS_REQUEST = 'ADD_UERS_REQUEST';
export const ADD_UERS_SUCCESS = 'ADD_UERS_SUCCESS';
export const ADD_UERS_FAILURE = 'ADD_UERS_FAILURE';

export const EDIT_UERS_REQUEST = 'EDIT_UERS_REQUEST';
export const EDIT_UERS_SUCCESS = 'EDIT_UERS_SUCCESS';
export const EDIT_UERS_FAILURE = 'EDIT_UERS_FAILURE';
